name: Deploy Telegram Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyrogram python-dotenv pytz yt-dlp instaloader requests
    
    - name: Run syntax check
      run: |
        python -m py_compile main.py
        python -m py_compile bot/client.py
        python -m py_compile bot/config.py

  deploy-heroku:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "your-bot-name"
        heroku_email: "your-email@example.com"
        
  deploy-railway:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Railway
      run: |
        npm install -g @railway/cli
        railway login --token ${{secrets.RAILWAY_TOKEN}}
        railway up
        
  deploy-vps:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{secrets.VPS_HOST}}
        username: ${{secrets.VPS_USERNAME}}
        key: ${{secrets.VPS_SSH_KEY}}
        script: |
          cd /home/ubuntu/telegram-bot
          git pull origin main
          pip install -r requirements.txt
          sudo systemctl restart telegram-bot