name: Docker Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/telegram-video-bot:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/telegram-video-bot:${{ github.sha }}
    
    - name: Deploy to production
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/telegram-video-bot:latest
          docker stop telegram-bot || true
          docker rm telegram-bot || true
          docker run -d --name telegram-bot \
            -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
            -e TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }} \
            -e TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }} \
            -e ADMIN_IDS=${{ secrets.ADMIN_IDS }} \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/telegram-video-bot:latest