name: Run Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyrogram python-dotenv pytz yt-dlp instaloader requests
    
    - name: Create environment file
      run: |
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
        echo "TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }}" >> .env
        echo "TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }}" >> .env
        echo "ADMIN_IDS=${{ secrets.ADMIN_IDS }}" >> .env
    
    - name: Run bot
      run: |
        timeout 21000 python main.py || echo "Bot session completed"
    
  restart-bot:
    needs: run-bot
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Trigger restart
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'run-bot.yml'
          })